# Change for a JSON cfg file
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SCALE = 1
SCREEN_BACKGROUND_COLOR = (15, 90, 15)  # Forest green
FPS = -60 # LimitFPS
MAX_AUDIO_CHANNELS = 8
ENABLE_COLLISION_DEBUG = True

_CAM_BORDER_RADIUS = 300

