# Change for a JSON cfg file
SCREEN_WIDTH  = 1920
SCREEN_HEIGHT = 1080
SCREEN_SCALE  = 1
SCREEN_BACKGROUND_COLOR = (20, 20, 28)
FPS = -60
MAX_AUDIO_CHANNELS = 32
ENABLE_COLLISION_DEBUG  = False
ENABLE_MONOLITE_DEBUG   = False
_CAM_BORDER_RADIUS = 0
TILE_SIZE  = 32
CHUNK_SIZE = 16